# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20171110_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='estimated_duration',
            new_name='duration',
        ),
    ]
