# Generated by Django 2.0 on 2018-02-09 14:02

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20180203_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskexecution',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
