# Generated by Django 2.0 on 2018-03-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20180209_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='start',
            field=models.DateField(null=True),
        ),
    ]
