# Generated by Django 2.1 on 2018-08-21 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_task_start'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskExecution',
            new_name='TaskChunk',
        ),
        migrations.AlterField(
            model_name='taskchunk',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='task.Task'),
        ),
    ]
