# Generated by Django 2.1 on 2018-09-06 12:34

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_task_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskChunkSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DecimalField(decimal_places=2, default=1, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('start', models.DateField()),
                ('end', models.DateField(null=True)),
                ('last_scheduled_day', models.DateField(null=True)),
                ('completely_scheduled', models.BooleanField(default=False)),
                ('rule', models.CharField(choices=[('interval', 'schedule in an interval of a fixed number of days'), ('monthly', 'schedule on a specific day in an interval of a fixed number of months'), ('monthlyweekday', 'schedule on a specific weekday in an interval of a fixed number of months')], max_length=15)),
                ('interval_days', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('monthly_day', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('monthly_months', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('monthlyweekday_weekday', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('monthlyweekday_nth', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunk_series', to='task.Task')),
            ],
        ),
        migrations.AddField(
            model_name='taskchunk',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chunks', to='task.TaskChunkSeries'),
        ),
    ]
