# Generated by Django 2.1 on 2018-09-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_auto_20180906_1434'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskchunkseries',
            options={'verbose_name_plural': 'task chunk series'},
        ),
        migrations.AddField(
            model_name='task',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='taskchunk',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
