# Generated by Django 2.1 on 2018-09-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_auto_20180910_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskchunk',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
