# Generated by Django 2.0 on 2017-12-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20171111_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_schedule_duration',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
        ),
        migrations.AddField(
            model_name='user',
            name='default_schedule_full_duration_max',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
