# Generated by Django 2.1 on 2018-09-04 16:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20180821_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_schedule_duration',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='default_schedule_full_duration_max',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='workhours_weekday',
            field=models.DecimalField(decimal_places=2, default=8, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='workhours_weekend',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
    ]
